import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,signInAnonymously,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,doc,getDoc,setDoc,collection,query,where,orderBy,limit,getDocs,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";import{firebaseConfig}from"./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();const tgUser=tg?.initDataUnsafe?.user||null,telegramId=tgUser?.id?String(tgUser.id):null,name=tgUser?[tgUser.first_name,tgUser.last_name].filter(Boolean).join(" "):"Demo User";let me,userId,settings={watchReward:1,dailyAdLimit:20,referralReward:5,minimumWithdraw:100,minimumReferrals:5};const $=x=>document.getElementById(x);
async function settingsLoad(){let s=await getDoc(doc(db,"settings","appsettings"));if(s.exists())settings={...settings,...s.data()};$("watchReward").textContent=settings.watchReward;$("dailyLimit").textContent=settings.dailyAdLimit;$("refReward").textContent=settings.referralReward;$("minWithdraw").textContent=settings.minimumWithdraw;$("minReferrals").textContent=settings.minimumReferrals;$("withdrawAmount").min=settings.minimumWithdraw}
async function userLoad(){userId=telegramId||me.uid;let r=doc(db,"users",userId),s=await getDoc(r);if(!s.exists())await setDoc(r,{telegramId:telegramId||null,name,balance:0,referralCount:0,totalEarned:0,adsToday:0,lastAdDate:new Date().toISOString().slice(0,10),status:"active",createdAt:serverTimestamp()});s=await getDoc(r);let u=s.data();$("balance").textContent=Number(u.balance||0).toFixed(2);$("refCount").textContent=u.referralCount||0;$("adsToday").textContent=u.lastAdDate===new Date().toISOString().slice(0,10)?u.adsToday||0:0;$("welcome").textContent="Hi, "+(u.name||name);await history();await adminCheck()}
async function history(){try{let q=query(collection(db,"transactions"),where("userId","==",userId),orderBy("createdAt","desc"),limit(30)),s=await getDocs(q),e=$("historyList");e.innerHTML=s.empty?'<p class="muted">No transactions yet.</p>':"";s.forEach(d=>{let x=d.data(),dt=x.createdAt?.toDate?x.createdAt.toDate().toLocaleString():"—";e.innerHTML+=`<div class="row"><div><b>${x.type||"Transaction"}</b><small>${dt} · ${x.status||""}</small></div><b>₹${Number(x.amount||0).toFixed(2)}</b></div>`})}catch(e){$("historyList").textContent="History will work after final Firestore rules/backend setup."}}
async function adminCheck(){try{let s=await getDoc(doc(db,"admins",me.uid));if(s.exists()&&s.data().role==="admin"){$("adminNav").classList.remove("hide");adminUI()}}catch(e){}}
async function adminUI(){$("adminArea").innerHTML=`<div class="grid"><div class="stat"><b id="uc">—</b>Users</div><div class="stat"><b id="wc">—</b>Pending withdrawals</div></div><h3>App Settings</h3><label>Watch reward ₹</label><input id="sw" type="number" step=".01"><label>Daily ad limit</label><input id="sl" type="number"><label>Referral reward ₹</label><input id="sr" type="number" step=".01"><label>Minimum withdrawal ₹</label><input id="sm" type="number"><label>Minimum referrals</label><input id="sf" type="number"><button id="save">Save Settings</button><p id="msg" class="muted"></p><p class="muted">Reward crediting, referral validation, redeem-code redemption and withdrawals must be finalized by trusted server-side code.</p>`;$("sw").value=settings.watchReward;$("sl").value=settings.dailyAdLimit;$("sr").value=settings.referralReward;$("sm").value=settings.minimumWithdraw;$("sf").value=settings.minimumReferrals;$("save").onclick=async()=>{let n={watchReward:+$("sw").value,dailyAdLimit:+$("sl").value,referralReward:+$("sr").value,minimumWithdraw:+$("sm").value,minimumReferrals:+$("sf").value};await setDoc(doc(db,"settings","appsettings"),n,{merge:true});settings={...settings,...n};await settingsLoad();$("msg").textContent="Settings saved."};try{$("uc").textContent=(await getDocs(collection(db,"users"))).size;$("wc").textContent=(await getDocs(query(collection(db,"withdrawals"),where("status","==","pending")))).size}catch(e){}}
$("watchBtn").onclick=()=>$("watchNote").textContent="No reward was added. Connect the approved ad-network completion callback on the server before enabling rewards.";
$("copyRef").onclick=async()=>{let l=telegramId?`https://t.me/YOUR_BOT_USERNAME?start=ref_${telegramId}`:"Open this app inside Telegram to get your referral link.";$("refLink").textContent=l;try{await navigator.clipboard.writeText(l);$("copyRef").textContent="Copied!"}catch(e){}};
$("withdrawMethod").onchange=()=>{let u=$("withdrawMethod").value==="upi";$("upiLabel").classList.toggle("hide",!u);$("upiId").classList.toggle("hide",!u);$("redeemLabel").classList.toggle("hide",u);$("redeemCode").classList.toggle("hide",u)};
$("withdrawBtn").onclick=()=>$("withdrawStatus").textContent="Withdrawal backend is not enabled yet. This prevents unsafe client-side money changes.";
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{let p=b.dataset.page;if(!p)return;document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));$(p).classList.add("active");b.classList.add("active")});
onAuthStateChanged(auth,async u=>{if(u){me=u;try{await settingsLoad();await userLoad()}catch(e){console.error(e);$("welcome").textContent="Firebase rules/backend pending"}}});signInAnonymously(auth).catch(console.error);